# Generated by Django 4.1.1 on 2022-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
