# Generated by Django 4.1.1 on 2022-09-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='news'),
        ),
    ]
