# Generated by Django 4.1.1 on 2022-09-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0002_alter_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.DateField(),
        ),
    ]
