# Generated by Django 4.1.1 on 2022-09-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0002_alter_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='social_med/media/news'),
        ),
    ]
