# Generated by Django 4.1.1 on 2022-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0003_alter_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('COMPLETED', 'completed'), ('REJECTED', 'rejected')], max_length=100),
        ),
    ]
