# Generated by Django 4.1.1 on 2022-09-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0004_alter_news_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
