# Generated by Django 4.1.1 on 2022-09-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0005_apply_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='title',
            new_name='text',
        ),
    ]
