# Generated by Django 4.1.1 on 2022-09-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_med', '0006_rename_title_apply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='social_med.services'),
        ),
    ]
